Repository Yeungnam-Nyang/Yeungnam-Nyang-FE, pull requests merged in 2024-12, with the labels that each got.

#40 37 fixkakaomap error
  src/pages/CatsMap.jsx
Labels: 🐛fix

#42 🔖release:v 0.0.1
  src/App.jsx
  src/components/common/Header.jsx
  src/components/common/NavBar.jsx
  src/components/nyangmap/CatMarker.jsx
  src/components/nyangmap/KakaoMap.jsx
  src/components/post/DetailPostHeader.jsx
  src/hooks/test.txt
  src/hooks/useFileUpload.jsx
  src/pages/CatsMap.jsx
  src/pages/Post/DetailPost.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Post/WritePost.jsx
  src/store/test.txt
  src/utils/test.txt
Labels: 👷cicd, 🔖release

#46 🔖release:HTTPS 버젼 변경 배포
  package-lock.json
  package.json
  src/api/api.jsx
  src/components/common/Modal.jsx
  src/components/friend/FriendList.jsx
  src/components/nyangmap/NyangBox.jsx
  src/components/post/StopWatch.jsx
  src/components/test.txt
  src/hooks/useFileUpload.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Profile/MyProfile.jsx
Labels: 🔖release

#48 👷ci:HTTPS test
  index.html
  src/api/api.jsx
Labels: 💚build, 👷cicd

#49 👷ci:HTTPS TEST
  src/pages/Login/Login.jsx
Labels: 💚build, 👷cicd

#50 🐛fix:https변경
  src/pages/Login/Login.jsx
Labels: 💚build, 👷cicd

#54 🐛fix:main.yml변경
  .github/workflows/main.yml
Labels: 💚build, 👷cicd

#59 58 fixmulti error fix
  public/assets/images/test.txt
  public/assets/test.txt
  src/api/test.txt
  src/assets/font/BagelFatOne-Regular.ttf
  src/assets/font/Bungee-Regular.ttf
  src/assets/font/test.txt
  src/assets/images/404.png
  src/assets/images/Icon_account.png
  src/assets/images/Icon_cat.png
  src/assets/images/Icon_fire.png
  src/assets/images/Icon_house.png
  src/assets/images/Icon_paw-white.png
  src/assets/images/Icon_people.png
  src/assets/images/error.png
  src/assets/images/ex01.jpeg
  src/assets/images/icon_pow.png
  src/assets/images/logo-big.png
  src/assets/images/logo.png
  src/assets/images/marker.png
  src/assets/images/profile_default.png
  src/assets/images/shieldCat.png
  src/assets/images/spinner.gif
  src/assets/images/test.txt
  src/assets/sounds/cat.mp3
  src/assets/test.txt
  src/components/common/title.jsx
  src/components/friend/FriendList.jsx
  src/components/friend/FriendRequest.jsx
  src/components/main/PostPreview.jsx
  src/components/post/DetailPostHeader.jsx
  src/pages/Friend.jsx
  src/pages/FriendList.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/Scrap.jsx
  src/pages/TodayCat.jsx
  src/pages/test.jsx
  src/test/signup-test.jsx
Labels: ✅test

#63 Feature/friendandprofile
  src/App.jsx
  src/components/friend/FriendList.jsx
  src/pages/FriendProfile.jsx
  src/pages/Profile/MyProfile.css
  src/pages/Profile/MyProfile.jsx
Labels: ✨feat, ♻️refactor

#64 58 fixmulti error fix
  .github/workflows/main.yml
  index.html
  nginx.conf
  public/assets/images/test.txt
  public/assets/test.txt
  src/api/api.jsx
  src/api/test.txt
  src/assets/font/BagelFatOne-Regular.ttf
  src/assets/font/Bungee-Regular.ttf
  src/assets/font/test.txt
  src/assets/images/404.png
  src/assets/images/Icon_account.png
  src/assets/images/Icon_cat.png
  src/assets/images/Icon_fire.png
  src/assets/images/Icon_house.png
  src/assets/images/Icon_paw-white.png
  src/assets/images/Icon_people.png
  src/assets/images/error.png
  src/assets/images/ex01.jpeg
  src/assets/images/icon_pow.png
  src/assets/images/logo-big.png
  src/assets/images/logo.png
  src/assets/images/marker.png
  src/assets/images/profile_default.png
  src/assets/images/shieldCat.png
  src/assets/images/spinner.gif
  src/assets/images/test.txt
  src/assets/sounds/cat.mp3
  src/assets/test.txt
  src/components/common/Modal.jsx
  src/components/common/title.jsx
  src/components/friend/FriendList.jsx
  src/components/friend/FriendRequest.jsx
  src/components/main/PostPreview.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/DetailPostHeader.jsx
  src/pages/Friend.jsx
  src/pages/FriendList.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/Scrap.jsx
  src/pages/SignUp/SignUp2.jsx
  src/pages/TodayCat.jsx
  src/pages/test.jsx
  src/test/signup-test.jsx
Labels: 🐛fix, ♻️refactor

#66 65 refactfriend request and friend received
  public/assets/images/default_profile_gray.png
  src/App.jsx
  src/components/friend/FriendList.jsx
  src/components/friend/FriendRequest.jsx
  src/components/main/PostPreview.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/DetailPostHeader.jsx
  src/pages/Friend.jsx
  src/pages/FriendReceive.jsx
  src/pages/FriendSent.jsx
  src/pages/Main.jsx
  src/pages/Profile/MyProfile.jsx
Labels: ♻️refactor

#67 65 refactfriend request and friend received
  src/components/friend/FriendList.jsx
  src/components/main/PostPreview.jsx
  src/pages/Login/Login.jsx
Labels: ♻️refactor

#69 💚build:test
  src/components/main/PostPreview.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/DetailPostContent.jsx
  src/components/post/StopWatch.jsx
  src/pages/Post/DetailPost.jsx
Labels: 💚build

#71 💚build:test
  src/components/post/DetailPostContent.jsx
Labels: 💚build

#72 💚build:server url 변경
  src/components/post/DetailPostContent.jsx
Labels: 💚build

#73 💚build:server url 변경
  src/components/post/DetailPostContent.jsx
Labels: 💚build

#74 🔖release:v 0.0.1
  public/assets/images/default_profile_gray.png
  src/App.jsx
  src/components/common/Modal.jsx
  src/components/friend/FriendList.jsx
  src/components/friend/FriendRequest.jsx
  src/components/main/PostPreview.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/DetailPostHeader.jsx
  src/pages/Friend.jsx
  src/pages/FriendProfile.jsx
  src/pages/FriendReceive.jsx
  src/pages/FriendSent.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Profile/MyProfile.css
  src/pages/Profile/MyProfile.jsx
  src/pages/SignUp/SignUp2.jsx
Labels: 🔖release

#76 75 fixscrap route edit fix icon
  src/App.jsx
  src/components/main/PostPreview.jsx
  src/components/nyangmap/CatMarker.jsx
  src/components/nyangmap/KakaoMap.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/StopWatch.jsx
  src/hooks/useFileUpload.jsx
  src/hooks/useGeoLocation.jsx
  src/pages/Friend.jsx
  src/pages/FriendProfile.jsx
  src/pages/Login/FindId.jsx
  src/pages/Login/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Post/WritePost.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/SignUp/SignUp2.jsx
Labels: 🐛fix

#77 75 fixscrap route edit fix icon
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Wrapper.jsx
  src/components/main/PostPreview.jsx
  src/components/nyangmap/CatMarker.jsx
  src/components/nyangmap/KakaoMap.jsx
  src/components/post/DetailPostComment.jsx
  src/components/post/DetailPostHeader.jsx
  src/components/post/StopWatch.jsx
  src/hooks/useFileUpload.jsx
  src/hooks/useGeoLocation.jsx
  src/hooks/useLocationPermission.jsx
  src/pages/CatsMap.jsx
  src/pages/Friend.jsx
  src/pages/FriendProfile.jsx
  src/pages/FriendReceive.jsx
  src/pages/FriendSent.jsx
  src/pages/Login/FindId.jsx
  src/pages/Login/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/NotFound.jsx
  src/pages/Post/DetailPost.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Post/WritePost.jsx
  src/pages/Profile/EditProfile.jsx
  src/pages/Profile/EditProfile2.jsx
  src/pages/Profile/MyCats.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/Profile/SavedPosts.jsx
  src/pages/Scrap.jsx
  src/pages/SignUp/SignUP1.jsx
  src/pages/SignUp/SignUp2.jsx
  src/styles/animation.js
Labels: 🐛fix

#80 🔖release:V0.0.2
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/Wrapper.jsx
  src/components/nyangmap/KakaoMap.jsx
  src/components/post/DetailPostHeader.jsx
  src/hooks/useLocationPermission.jsx
  src/pages/CatsMap.jsx
  src/pages/Friend.jsx
  src/pages/FriendProfile.jsx
  src/pages/FriendReceive.jsx
  src/pages/FriendSent.jsx
  src/pages/Login/FindId.jsx
  src/pages/Login/FindPassword.jsx
  src/pages/Login/Login.jsx
  src/pages/Main.jsx
  src/pages/NotFound.jsx
  src/pages/Post/DetailPost.jsx
  src/pages/Post/EditPost.jsx
  src/pages/Post/WritePost.jsx
  src/pages/Profile/EditProfile.jsx
  src/pages/Profile/EditProfile2.jsx
  src/pages/Profile/MyCats.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/Profile/SavedPosts.jsx
  src/pages/Scrap.jsx
  src/pages/SignUp/SignUP1.jsx
  src/pages/SignUp/SignUp1.css
  src/pages/SignUp/SignUp2.jsx
  src/styles/animation.js
  vite.config.js
Labels: 🔖release

#82 🐛fix:카카오맵 오류 잠정적 해결
  src/components/nyangmap/CatMarker.jsx
  src/components/nyangmap/KakaoMap.jsx
  src/main.jsx
  src/pages/Friend.jsx
Labels: 🐛fix, 🚑hotfix
